-- PRESTADORES 
INSERT INTO tipoprestador(CodTipoPrestador, Funcao) 
VALUES 
(1, 'RECEPCIONISTA'),
(2, 'DENTISTA');

-- PERMISSÕES
-- INSERT INTO Roles(CodRoles, Nome)
-- VALUES 
 -- (1, 'ADMIN'),
-- (2, 'DENTISTA'),
-- (3, 'RECEPCIONISTA'),
-- (4, 'USER');

-- PROCEDIMENTOS
INSERT INTO procedimentos (codProcedimento, descricaoProcedimento)
VALUES
(1, 'EXTRAÇÃO'),
(2, 'CANAL'),
(3, 'RESTAURAÇÃO'),
(4, 'PINO'),
(5, 'COROA');

-- SERVIÇOS
INSERT INTO procedimentos (codProcedimento, descricaoProcedimento)
VALUES
(6, 'LIMPEZA'),
(7, 'CLAREAMENTO'),
(8, 'APARELHOS ORTODÔNTICOS'),
(9, 'TRATAMENTO DE GENGIVAS'),
(10, 'FACETAS'),
(11, 'MANUTENÇÃO'),
(12, 'FRENECTOMIA'),
(13, 'REMOÇÃO DE LESÃO PATOLÓGICA'),
(14, 'CIRURGIA DE REGULARIZAÇÃO DE REBORDO ALVEOLAR'),
(15, 'PRÓTESE ADESIVA'),
(16, 'AUMENTO DE COROA CLÍNICA'),
(17, 'GENGIVOPLASTIA'),
(18, 'PROVISÓRIO'),
(19, 'PLACA PARA BRUXISMO'),
(20, 'CONTENÇÃO');

-- ARCADA SUPERIOR (16 DENTES)
INSERT INTO dente (codDente, nomeDente, NumeroDente) 
VALUES 
(1, 'TERCEIRO MOLAR SUPERIOR DIREITO (SISO)', 18),
(2, 'SEGUNDO MOLAR SUPERIOR DIREITO', 17),
(3, 'PRIMEIRO MOLAR SUPERIOR DIREITO', 16),
(4, 'SEGUNDO PRÉ-MOLAR SUPERIOR DIREITO', 15),
(5, 'PRIMEIRO PRÉ-MOLAR SUPERIOR DIREITO', 14),
(6, 'CANINO SUPERIOR DIREITO', 13),
(7, 'INCISIVO LATERAL SUPERIOR DIREITO', 12),
(8, 'INCISIVO CENTRAL SUPERIOR DIREITO', 11),
(9, 'INCISIVO CENTRAL SUPERIOR ESQUERDO', 21),
(10, 'INCISIVO LATERAL SUPERIOR ESQUERDO', 22),
(11, 'CANINO SUPERIOR ESQUERDO', 23),
(12, 'PRIMEIRO PRÉ-MOLAR SUPERIOR ESQUERDO', 24),
(13, 'SEGUNDO PRÉ-MOLAR SUPERIOR ESQUERDO', 25),
(14, 'PRIMEIRO MOLAR SUPERIOR ESQUERDO', 26),
(15, 'SEGUNDO MOLAR SUPERIOR ESQUERDO', 27),
(16, 'TERCEIRO MOLAR SUPERIOR ESQUERDO (SISO)', 28);

-- ARCADA INFERIOR (16 DENTES)
INSERT INTO Dente (CodDente, nomeDente, NumeroDente) 
VALUES 
(17, 'TERCEIRO MOLAR INFERIOR DIREITO (SISO)', 48),
(18, 'SEGUNDO MOLAR INFERIOR DIREITO', 47),
(19, 'PRIMEIRO MOLAR INFERIOR DIREITO', 46),
(20, 'SEGUNDO PRÉ-MOLAR INFERIOR DIREITO', 45),
(21, 'PRIMEIRO PRÉ-MOLAR INFERIOR DIREITO', 44),
(22, 'CANINO INFERIOR DIREITO', 43),
(23, 'INCISIVO LATERAL INFERIOR DIREITO', 42),
(24, 'INCISIVO CENTRAL INFERIOR DIREITO', 41),
(25, 'INCISIVO CENTRAL INFERIOR ESQUERDO', 31),
(26, 'INCISIVO LATERAL INFERIOR ESQUERDO', 32),
(27, 'CANINO INFERIOR ESQUERDO', 33),
(28, 'PRIMEIRO PRÉ-MOLAR INFERIOR ESQUERDO', 34),
(29, 'SEGUNDO PRÉ-MOLAR INFERIOR ESQUERDO', 35),
(30, 'PRIMEIRO MOLAR INFERIOR ESQUERDO', 36),
(31, 'SEGUNDO MOLAR INFERIOR ESQUERDO', 37),
(32, 'TERCEIRO MOLAR INFERIOR ESQUERDO (SISO)', 38);